attributes of array :

1. dtype
2.shape
3.size
4.ndim

In [1]:
import numpy as np

In [2]:
arr1=np.array([23,'fbs',3.14])

In [4]:
arr1

array(['23', 'fbs', '3.14'], dtype='<U32')

size gives no. of elements

In [5]:
arr1.size

3

In [8]:
arr1.dtype

dtype('<U32')

shape gives (rows,columns) 

In [9]:
arr1.shape

(3,)

ndim gives no.of diamentions check to no. of square bracet. count it []

In [10]:
arr1.ndim

1

In [11]:
arr2 = np.array([x for x in range (10001,20001)])

In [12]:
arr2

array([10001, 10002, 10003, ..., 19998, 19999, 20000], shape=(10000,))

In [14]:
arr3 = np.array([x for x in range (1,100)])
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [17]:
arr = np.array([12,56,90,3])
ar1 =np.array([34,67,89,90])

In [18]:
arr + ar1

array([ 46, 123, 179,  93])

In [30]:
arr >25

array([False,  True,  True, False])

In [19]:
arr * ar1

array([ 408, 3752, 8010,  270])

In [20]:
arr - ar1

array([-22, -11,   1, -87])

In [21]:
arr.size

4

In [22]:
arr4 = np.array([23.5,6,8,90])

In [23]:
arr4

array([23.5,  6. ,  8. , 90. ])

gives folat in all int

In [24]:
arr5 = np.array([2,4,5,78.89,90.0,"sakshi","purva"])
arr5

array(['2', '4', '5', '78.89', '90.0', 'sakshi', 'purva'], dtype='<U32')

gives in string format because of whivh is highest byte then array convert it that format 