In [1]:
a=10

In [2]:
b=20

In [3]:
c=a+b

In [4]:
c

30

In [5]:
a=20
b=40
c=a-b
c

-20

In [6]:
a=10

In [7]:
b=3

In [8]:
c=a^b

In [9]:
c

9

In [10]:
c=a*a*a

In [11]:
c

1000

In [20]:
a=3
b=4
c=1
for i in range(b):
    c = c*a
print(c)

81


In [4]:
def addition(a,b):
    c= a+b

In [5]:
a=10
b=20
addition(a,b)

In [8]:
import numpy as np

we are learining numpy

addition of 2 list of index

In [10]:
li1 = [1,2,3,4]
li2=[5,6,7,8]
res =[]
for i in range(len(li1)):
    res.append(li1[i]+li2[i])
print (res)


[6, 8, 10, 12]


we use array 
array : is homogenous collection of data (similar type of data).
        order collection (we do indexing)

In [12]:
li1 =[1,2,3]
li2 =[4,5,6]
res = list(map(lambda x,y : x+y ,li1,li2))
print(res)

[5, 7, 9]


In [18]:
li1 =[1,2,3]
li2 =[4,5,6]
#li3 = li1-li2 error
#li1 *5 repet the list

In [19]:
arr1 = np.array([1,2,4,5])
arr1

array([1, 2, 4, 5])

In [20]:
arr2 = np.array([5,6,7,8])
arr2

array([5, 6, 7, 8])

In [22]:
arr3 = arr1 + arr2
arr3

array([ 6,  8, 11, 13])

In [23]:
arr3 = arr1 - arr2
arr3

array([-4, -4, -3, -3])

In [25]:
arr3 = np.array([10,20,30,40])
arr3 *5

array([ 50, 100, 150, 200])

In [ ]:
## vectorization 
1. when we 