In [3]:
import numpy as np

like range in python or like for loop

In [5]:
arr1 = np.arange(1,21)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [13]:
arr2 = np.random.randint(1,100,15)
arr2

array([68, 59, 30, 71, 27, 78, 84, 22, 37, 79, 69, 81, 56, 24, 55],
      dtype=int32)

functions in built 

In [11]:
arr1

array([43, 80, 79, 30, 34, 51, 12, 74, 75, 51, 43, 74, 56, 70, 25],
      dtype=int32)

In [14]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [15]:
arr.min()

np.int64(1)

In [16]:
arr.max()

np.int64(20)

In [17]:
arr.sum()

np.int64(210)

mean means avg 

In [18]:
arr.mean()

np.float64(10.5)

In [20]:
arr.size

20

In [23]:
arr.sort

<function ndarray.sort(axis=-1, kind=None, order=None, *, stable=None)>

In [25]:
np.sort(arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

reshape array

In [28]:
arr3 = np.random.randint(1,100,25)
arr3

array([84, 46, 93, 46, 16, 54, 49, 35, 67, 97, 91, 64, 20, 45, 48, 33, 94,
       88, 35, 20, 44, 74, 18, 60, 59], dtype=int32)

In [33]:
arr3 = arr3.reshape(3,5)
arr3

ValueError: cannot reshape array of size 25 into shape (3,5)

In [35]:
arr4 = np.arange(1,13)
arr4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [36]:
arr4=arr4.reshape(3,4)
arr4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [37]:
arr4[::-1]

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [38]:
arr4[1,3]

np.int64(8)

In [39]:
arr4[2,0:2]

array([ 9, 10])

In [40]:
arr4[:3]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [41]:
arr4[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])