In [1]:
import pandas as pd

In [3]:
s1 = pd.Series([1,2,4,6,7,8])
s1
#given index with elements

0    1
1    2
2    4
3    6
4    7
5    8
dtype: int64

In [5]:
#change the index
s1 = pd.Series([1,2,3,4,5],index = ['a','b','c','d','e'])
s1

a    1
b    2
c    3
d    4
e    5
dtype: int64

serise : is a collection of labelled data

In [7]:
intake = pd.Series([60,80,90],index = ['civil','IT','computer'])
intake

civil       60
IT          80
computer    90
dtype: int64

different way to create serise

In [8]:
#1.dict
top = pd.Series({"math":90,"sci":80,"eng":60})
top

math    90
sci     80
eng     60
dtype: int64

In [10]:
#2 list
import numpy as np
arr = np.arange(1,11)
s2 = pd.Series(arr)
s2

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

operation on series 

In [13]:
s3 = pd.Series(np.arange(21,30))
s4 = pd.Series(np.arange(31,40))
s3


0    21
1    22
2    23
3    24
4    25
5    26
6    27
7    28
8    29
dtype: int64

In [14]:
s4

0    31
1    32
2    33
3    34
4    35
5    36
6    37
7    38
8    39
dtype: int64

In [15]:
s3 + s4

0    52
1    54
2    56
3    58
4    60
5    62
6    64
7    66
8    68
dtype: int64

In [16]:
s3 * s4

0     651
1     704
2     759
3     816
4     875
5     936
6     999
7    1064
8    1131
dtype: int64

In [17]:
s3 - s4

0   -10
1   -10
2   -10
3   -10
4   -10
5   -10
6   -10
7   -10
8   -10
dtype: int64

index should be same then perfrom operation

In [18]:
s3

0    21
1    22
2    23
3    24
4    25
5    26
6    27
7    28
8    29
dtype: int64

in built functions of Series : 

In [19]:
s3.min()

np.int64(21)

In [20]:
s3.max()

np.int64(29)

In [21]:
s3.mean()

np.float64(25.0)

In [22]:
s3.size

9

In [23]:
s3.sum()

np.int64(225)

conditional statements :

In [24]:
s3

0    21
1    22
2    23
3    24
4    25
5    26
6    27
7    28
8    29
dtype: int64

In [25]:
s3[ s3 %2 == 0]

1    22
3    24
5    26
7    28
dtype: int64

In [26]:
s3 > s4

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
dtype: bool

In [32]:
s5 = pd.Series(np.arange(21,30))
s5

0    21
1    22
2    23
3    24
4    25
5    26
6    27
7    28
8    29
dtype: int64

In [33]:
s5[s5 > s5[4]]

5    26
6    27
7    28
8    29
dtype: int64

In [37]:
arr

array([1, 0, 3, 0, 5, 0, 7, 0, 9, 0])

even no put as 0 that place 

In [40]:

arr1= np.where(arr %2 == 0,0,arr)
arr1

array([1, 0, 3, 0, 5, 0, 7, 0, 9, 0])

In [41]:
arr1

array([1, 0, 3, 0, 5, 0, 7, 0, 9, 0])

In [43]:
s3

0    21
1    22
2    23
3    24
4    25
5    26
6    27
7    28
8    29
dtype: int64

In [44]:
s4 = pd.Series([3,6,3,89,2,3,4,3,5,3,9])
s4

0      3
1      6
2      3
3     89
4      2
5      3
6      4
7      3
8      5
9      3
10     9
dtype: int64

mode gives max count of element

In [45]:
s4.mode()

0    3
dtype: int64