In [1]:
import numpy as np

linspace : linearly separeted no.

In [2]:
arr1 =np.linspace(1,11)
arr1

array([ 1.        ,  1.20408163,  1.40816327,  1.6122449 ,  1.81632653,
        2.02040816,  2.2244898 ,  2.42857143,  2.63265306,  2.83673469,
        3.04081633,  3.24489796,  3.44897959,  3.65306122,  3.85714286,
        4.06122449,  4.26530612,  4.46938776,  4.67346939,  4.87755102,
        5.08163265,  5.28571429,  5.48979592,  5.69387755,  5.89795918,
        6.10204082,  6.30612245,  6.51020408,  6.71428571,  6.91836735,
        7.12244898,  7.32653061,  7.53061224,  7.73469388,  7.93877551,
        8.14285714,  8.34693878,  8.55102041,  8.75510204,  8.95918367,
        9.16326531,  9.36734694,  9.57142857,  9.7755102 ,  9.97959184,
       10.18367347, 10.3877551 , 10.59183673, 10.79591837, 11.        ])

rand :any 10 no.randomly genereted 0-10

In [3]:
arr2 = np.random.rand(10)
arr2

array([0.41345329, 0.51289209, 0.93952613, 0.44577921, 0.00847415,
       0.32864249, 0.4243954 , 0.22669297, 0.83576887, 0.19859094])

array with 1 created automatically.

In [4]:
arr3=np.ones(5)
arr3

array([1., 1., 1., 1., 1.])

In [5]:
arr4 = np.zeros(10,dtype='int')
arr4 # shift tab u get syntax of zeros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
arr5 = np.eye(3,3)
arr5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
arr6 = np.arange(1,21)
arr6

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [11]:
arr7 = np.random.randint(1,100,15)
arr7

array([10, 91, 77, 48, 78, 60,  6, 47, 19, 61, 79, 73, 17, 10, 55],
      dtype=int32)

axise = 0 .... row
axise =1 ... column

In [16]:
arr =  np.random.randint(1,100,30).reshape(6,5)
arr

array([[99,  6, 80, 60, 87],
       [53, 62, 77, 24,  3],
       [22, 97, 99, 26, 50],
       [47, 63, 19, 50, 19],
       [50, 83, 96, 30, 77],
       [83, 18, 73, 71, 41]], dtype=int32)

In [17]:
arr.min(axis =1)

array([ 6,  3, 22, 19, 30, 18], dtype=int32)

In [18]:
arr.argmin()

np.int64(9)

In [19]:
arr.argmax()

np.int64(0)

In [20]:
arr.min()

np.int32(3)

boradcasting: 1d arry and 2d array addition indexwise

In [23]:
arr8 = np.array([45,34,67,89])
arr9 = np.array([[10,20,30,40],
                 [50,60,70,80]])
arr10 = arr8 + arr9
arr10

array([[ 55,  54,  97, 129],
       [ 95,  94, 137, 169]])

operation on 1 d array 

In [24]:
arr11 = np.array([45,34,67,89])
arr12= np.array([10,20,30,40])
arr13 = arr11 +arr12
arr13

array([ 55,  54,  97, 129])

conditinal selection :

In [25]:
arr14 = np.random.randint(1,100,15)
arr14

array([56,  4, 23, 80, 28, 59, 79, 51, 19, 82, 85, 86,  2, 34, 83],
      dtype=int32)

In [26]:
arr14 > 50

array([ True, False, False,  True, False,  True,  True,  True, False,
        True,  True,  True, False, False,  True])

fetch the element proper not given true / flase :

In [27]:
arr14[arr14 >50 ]

array([56, 80, 59, 79, 51, 82, 85, 86, 83], dtype=int32)

even elements:

In [28]:
arr14

array([56,  4, 23, 80, 28, 59, 79, 51, 19, 82, 85, 86,  2, 34, 83],
      dtype=int32)

In [29]:
arr14[arr14 %2 == 0 ]


array([56,  4, 80, 28, 82, 86,  2, 34], dtype=int32)

multiple of 3

In [30]:
arr14 [ arr14 %3 == 0]

array([51], dtype=int32)

find out greaterthen 50 and lessthen 90 

In [33]:
arr14[ (arr14 > 50) & (arr14 < 90) ]

array([56, 80, 59, 79, 51, 82, 85, 86, 83], dtype=int32)