# Assignment 2

In [1]:
import numpy as np

**1. Create a NumPy array containing integers from 0 to 9.**

In [2]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Create a NumPy array from a given Python list [10, 20, 30, 40, 50].**

In [3]:
arr1 = np.array([10, 20, 30, 40, 50])
arr1

array([10, 20, 30, 40, 50])

**Create a 2D array (3x3) with values ranging from 0 to 8.**

In [4]:
arr3 = np.arange(0,9).reshape(3,3)
arr3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**Given a 2D array, find its shape and size. Create a 5x4 array with random integers between
1 and 100, and print the shape and size.**

In [11]:
arr4 = np.random.randint(1,101,20).reshape(5,4)
arr4

array([[84, 58, 50,  9],
       [64, 48,  1, 64],
       [23, 22, 90, 94],
       [24, 50, 43, 25],
       [51, 29, 55, 97]], dtype=int32)

In [12]:
arr4.shape

(5, 4)

In [13]:
arr4.size

20

**5. Create a 3x3 array of integers and access:**


In [14]:
arr5 = np.arange(1,10).reshape(3,3)
arr5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**a. The second element of the first row.**


In [15]:
arr5[0,1]

np.int64(2)

**b. The third column of the 2nd row.**


In [17]:
arr5[1,2]

np.int64(6)

**c. A subarray with the first two rows and last two columns.**

In [22]:
arr5[:2,1:]

array([[2, 3],
       [5, 6]])

**6.Create a 1D array of 12 elements. Reshape it into a 3x4 2D array.**

In [23]:
arr6=np.arange(1,13).reshape(3,4)
arr6

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

**7. Reshape a 3x3 matrix into a 1D array.**

In [25]:
arr7 = np.arange(0,9).reshape(3,3)
arr7

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
arr7.reshape(-1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

**Create two arrays of shape (2, 3): arr1 and arr2. Perform element-wise addition,
subtraction, multiplication, and division on them.**

In [30]:
arrr1=np.arange(1,7).reshape(2,3)
arrr1

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
arrr2=np.arange(11,17).reshape(2,3)
arrr2

array([[11, 12, 13],
       [14, 15, 16]])

In [32]:
arrr1 + arrr2

array([[12, 14, 16],
       [18, 20, 22]])

In [33]:
arrr1 - arrr2

array([[-10, -10, -10],
       [-10, -10, -10]])

In [34]:
arrr1 * arrr2

array([[11, 24, 39],
       [56, 75, 96]])

In [35]:
arrr1 / arrr2

array([[0.09090909, 0.16666667, 0.23076923],
       [0.28571429, 0.33333333, 0.375     ]])

**9. Use NumPy's built-in functions to compute the sum, mean, and standard deviation of a
given array.**

In [36]:
arr9 = np.arange(1,9)
arr9

array([1, 2, 3, 4, 5, 6, 7, 8])

In [37]:
arr9.sum()

np.int64(36)

In [38]:
arr9.mean()

np.float64(4.5)

In [39]:
arr9.std()

np.float64(2.29128784747792)

**10.Create a 2x2 matrix A and a 2x2 matrix B. Perform matrix multiplication using np.dot() or
the @ operator.**

In [40]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [41]:
b = np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [42]:
a @ b

array([[19, 22],
       [43, 50]])

In [44]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

**11. Find the transpose of matrix A and matrix B.**

In [74]:
a

array([[1, 2],
       [3, 4]])

In [75]:
b

array([[5, 6],
       [7, 8]])

In [76]:
a.T

array([[1, 3],
       [2, 4]])

In [77]:
b.T

array([[5, 7],
       [6, 8]])

**12. Create a 3x3 array and a 1D array with 3 elements. Add the 1D array to the 2D array.
Explain how broadcasting works in this operation.**


In [55]:
m1 = np.array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
m2 = np.array([10,20,30])

In [60]:
m1 + m2

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39]])

**13. Create a 4x4 array of random integers. Find the maximum, minimum, and mean of the
entire array.**


In [63]:
arr13 = np.random.randint(1,100,16).reshape(4,4)
arr13

array([[33, 93, 88,  9],
       [ 6, 25, 48, 23],
       [96, 70, 50, 94],
       [71, 82, 93, 65]], dtype=int32)

In [64]:
arr13.min()

np.int32(6)

In [65]:
arr13.min()

np.int32(6)

In [66]:
arr13.mean()

np.float64(59.125)

**14. Find the row-wise and column-wise sums.**


In [67]:
arr13

array([[33, 93, 88,  9],
       [ 6, 25, 48, 23],
       [96, 70, 50, 94],
       [71, 82, 93, 65]], dtype=int32)

In [69]:
arr13.sum(axis =1) #column

array([223, 102, 310, 311])

In [70]:
arr13.sum(axis= 0) # row

array([206, 270, 279, 191])

**15. Generate an array of 10 random integers between 1 and 50.**


In [71]:
arr15 = np.random.randint(1,51,10)
arr15

array([ 1, 14, 46,  2,  1, 30, 48, 45,  7, 27], dtype=int32)

**16. Generate a 5x5 matrix of random floats between 0 and 1.**

In [73]:
arr16 = np.random.rand(5,5)
arr16

array([[7.11631357e-01, 9.96990557e-01, 4.01586517e-01, 8.87419571e-01,
        4.50832221e-01],
       [6.58451315e-01, 1.92154668e-04, 8.30068828e-01, 2.35324772e-01,
        2.30848734e-01],
       [4.72729249e-01, 2.21159710e-01, 9.46075476e-01, 8.58214651e-01,
        3.45265532e-01],
       [9.63662153e-01, 1.04761166e-01, 2.56962352e-01, 4.03499281e-01,
        1.31025320e-01],
       [4.12509758e-01, 6.05954825e-01, 4.07400657e-01, 1.64290603e-01,
        6.98979309e-01]])