# Assigment 1

In [1]:
import numpy as np

**Q1. Write code to create a 4x3 matrix with values ranging from 2 to 13.**

In [4]:
arr = np.arange(2,14).reshape(4,3)

In [5]:
arr

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

**q2.Write code to replace the odd numbers by -1 in the array created by using
random.randint( 1 , 50,20)**

In [23]:
array = np.random.randint(1,50,20)
array

array([27, 16, 39, 25, 47, 20, 30, 43,  8, 40, 27, 31, 20,  8, 12, 31, 19,
       26, 35, 37], dtype=int32)

In [24]:
array[array %2 != 0] = -1
array

array([-1, 16, -1, -1, -1, 20, 30, -1,  8, 40, -1, -1, 20,  8, 12, -1, -1,
       26, -1, -1], dtype=int32)

**Q3.Perform the following operations on an array of mobile phones prices 6999, 7500,
11999, 27899, 14999, 9999.**


**A.Create a 1d-array of mobile phones prices**

In [39]:
prices=np.array([6999, 7500, 11999, 27899, 14999, 9999])
prices

array([ 6999,  7500, 11999, 27899, 14999,  9999])

**B.Convert this array to float type**

In [41]:
prices =prices.astype(float)
prices

array([ 6999.,  7500., 11999., 27899., 14999.,  9999.])

**c. Append a new mobile having price of 13999 Rs. to this array**


In [53]:
prices =np.append(prices,13999)
prices

array([ 6999.,  7500., 11999., 27899., 14999.,  9999., 13999.])

**d. Reverse this array of mobile phones prices**


In [54]:
rev = prices[::-1]
rev

array([13999.,  9999., 14999., 27899., 11999.,  7500.,  6999.])

**e. Apply GST of 18% on mobile phones prices and update this array.**


In [55]:
gst = prices *1.18
gst

array([ 8258.82,  8850.  , 14158.82, 32920.82, 17698.82, 11798.82,
       16518.82])

**f. Sort the array in descending order of price**


In [56]:
desc = np.sort(prices)[::-1]
desc

array([27899., 14999., 13999., 11999.,  9999.,  7500.,  6999.])

**g. What is the average mobile phone price**


In [57]:
avg = prices.mean()
avg

np.float64(13342.0)

**h. What is the difference b/w maximum and minimum price**

In [58]:
diff =prices.max()
diff

np.float64(27899.0)

In [59]:
dif =prices.min()
dif

np.float64(6999.0)

**Q4.Find out the indices of non zero element in given array
[1,2,0,0,4,0]**

In [60]:
arr2 =np.array([1,2,0,0,4,0])
arr2

array([1, 2, 0, 0, 4, 0])

In [61]:
indices = np.nonzero(arr2)
indices

(array([0, 1, 4]),)